# -*- coding: utf-8 -*-
"""Dependency Estimation and Analysis Model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Q_-hh2UhJI7MIYeLgpfIv3JVyDcHRVn
"""

# prompt: import the excel file and put it within a pandas dataframe.

!pip install openpyxl
import pandas as pd

# Assuming the file is named 'your_excel_file.xlsx' and is in the current directory
df = pd.read_excel('Combined_Training_Data_Final.xlsx')

df.info()

"""# Task
Analyze the dependencies between requirement statements in the DataFrame "requirements.csv" by pairing all statements, classifying the pairs using a RoBERTa model, building a dependency map, and deriving structural features such as the number of dependencies, the number of requirements supported by each requirement, and whether a requirement is a root or leaf requirement. Finally, integrate these features into the original DataFrame and display the result.

## Pair requirement statements

### Subtask:
Generate all possible pairs of requirement statements from the loaded DataFrame.

**Reasoning**:
Generate all unique pairs of requirement statements from the 'Requirement_Text' column of the DataFrame.

## Prepare data for classification

### Subtask:
Format the generated pairs as input for the RoBERTa-based binary classifier.

**Reasoning**:
Iterate through the requirement pairs and format them as input for the RoBERTa model.

## Classify pairs

### Subtask:
Use the RoBERTa model to classify each pair as dependent or not.

**Reasoning**:
Import necessary libraries and classes for using a pre-trained RoBERTa model, load the model and tokenizer, tokenize the formatted pairs, prepare input tensors, pass through the model, apply sigmoid, classify, and store results.

## Build dependency map

### Subtask:
Create a dictionary representing the dependency map based on the classification results.

**Reasoning**:
Initialize an empty dictionary and iterate through the requirement pairs and classification results to build the dependency map based on a classification result of 1.

**Reasoning**:
The variable `requirement_pairs` is not defined. I need to regenerate the `requirement_pairs` list and the `classified_results` list to proceed with creating the dependency map.

**Reasoning**:
The DataFrame `df` is not defined. I need to load the data into the DataFrame before I can access the 'Requirement_Text' column and proceed with generating pairs and building the dependency map.

**Reasoning**:
The pandas library is not imported, which is causing the `NameError`. I need to import pandas to read the Excel file into a DataFrame.

# Task
Train a RoBERTa-based binary classifier model to identify dependency relationships between pairs of requirement statements using the data in "Combined_Training_Data_Final.xlsx". The model should infer the binary dependency from the 'Num_Dependencies', 'Num_Supported_By', 'Is_Leaf_Requirement', and 'Is_Root_Requirement' columns. After training, save the model and tokenizer for later use in a FastAPI application. Finally, use the trained model to build a dependency map and derive the structural features ('Num_Dependencies', 'Num_Supported_By', 'Is_Root_Requirement', and 'Is_Leaf_Requirement') for each requirement, adding these as new columns to the original dataset.

## Load data

### Subtask:
Load the "Combined_Training_Data_Final.xlsx" file into a pandas DataFrame.

**Reasoning**:
The pandas library is not imported, which is causing the `NameError`. I need to import pandas to read the Excel file into a DataFrame.

## Prepare training data

### Subtask:
Generate pairs of requirement statements and determine the dependency label (0 or 1) for each pair based on the existing dependency-related columns (`Num_Dependencies`, `Num_Supported_By`, `Is_Leaf_Requirement`, and `Is_Root_Requirement`) in the dataset. This step needs careful consideration to correctly infer the dependency relationship from the existing features.

**Reasoning**:
I need to generate pairs of requirement statements and determine a dependency label for each pair based on the structural features in the DataFrame to create the training data for the classifier.

## Split data

### Subtask:
Split the prepared data into training and validation sets.

**Reasoning**:
Split the prepared training data into training and validation sets using train_test_split from sklearn.

## Load and prepare roberta model

### Subtask:
Load a pre-trained RoBERTa model and tokenizer for sequence classification and prepare the data for the model by tokenizing and creating input tensors.

**Reasoning**:
Import necessary libraries and classes for using a pre-trained RoBERTa model, load the model and tokenizer, tokenize the training and validation texts, and prepare input tensors and label tensors.

**Reasoning**:
The previous code block failed due to a conflict with TensorFlow's type registration, likely caused by importing `transformers` after TensorFlow has already been partially loaded in the environment. To resolve this, I need to restart the execution environment to clear the TensorFlow state and then re-run the code that loads the data, splits it, and prepares it for the RoBERTa model. Since the previous steps for data loading and splitting were successful, I will combine them with the current subtask's code into a single block to ensure they are executed in the correct order after the restart.

## Load and prepare roberta model (retry)

### Subtask:
Load a pre-trained RoBERTa model and tokenizer for sequence classification and prepare the data for the model by tokenizing and creating input tensors. This is a retry attempt to address the persistent TensorFlow environment conflict encountered previously.

**Reasoning**:
I need to load the RoBERTa model and tokenizer and prepare the data by tokenizing and creating input tensors. I will include imports and the necessary code to perform these steps.

## Train roberta model

### Subtask:
Train the RoBERTa model on the training data and evaluate it on the validation set.

**Reasoning**:
I need to define the training arguments, initialize the Trainer, train the model, and evaluate it, incorporating the data preparation steps from previous successful attempts to ensure all necessary variables are defined.

## Save model and tokenizer

### Subtask:
Save the trained RoBERTa model and tokenizer to files so they can be loaded later in a different environment.

**Reasoning**:
Save the trained RoBERTa model and tokenizer to specified directories.

**Reasoning**:
The variables `model` and `tokenizer` are not defined because the previous code blocks failed to load them due to an environment error. I need to include the code to load the model and tokenizer again before saving them. I will also include the data loading and preparation steps to ensure all necessary variables are available.
"""

from transformers import RobertaForSequenceClassification, RobertaTokenizer, TrainingArguments, Trainer

import pandas as pd

# Assuming the file is named 'Combined_Training_Data_Final.xlsx' and is in the current directory
df = pd.read_excel('Combined_Training_Data_Final.xlsx')

requirement_pairs = []
requirements = df['Requirement_Text'].tolist()

for i in range(len(requirements)):
    for j in range(i + 1, len(requirements)):
        requirement_pairs.append((requirements[i], requirements[j]))

print(f"Generated {len(requirement_pairs)} unique pairs.")

"""## Prepare data for classification

### Subtask:
Format the generated pairs as input for the RoBERTa-based binary classifier.

**Reasoning**:
Iterate through the requirement pairs and format them as input for the RoBERTa model.
"""

formatted_pairs = []
for req1, req2 in requirement_pairs:
    formatted_pairs.append({'text': f'{req1} [SEP] {req2}'})

print(f"Formatted {len(formatted_pairs)} pairs for RoBERTa input.")

"""## Prepare training data

### Subtask:
Generate pairs of requirement statements and determine the dependency label (0 or 1) for each pair based on the existing dependency-related columns (`Num_Dependencies`, `Num_Supported_By`, `Is_Leaf_Requirement`, and `Is_Root_Requirement`) in the dataset. This step needs careful consideration to correctly infer the dependency relationship from the existing features.

**Reasoning**:
I need to generate pairs of requirement statements and determine a dependency label for each pair based on the structural features in the DataFrame to create the training data for the classifier.
"""

training_data = []
requirements = df[['Requirement_Text', 'Is_Leaf_Requirement', 'Is_Root_Requirement']].to_dict('records')

for i in range(len(requirements)):
    for j in range(i + 1, len(requirements)):
        req1 = requirements[i]
        req2 = requirements[j]

        # Infer dependency based on the simplified heuristic
        is_req1_leaf = req1['Is_Leaf_Requirement'] == 1
        is_req1_root = req1['Is_Root_Requirement'] == 1
        is_req2_leaf = req2['Is_Leaf_Requirement'] == 1
        is_req2_root = req2['Is_Root_Requirement'] == 1

        # Heuristic: Label 1 if neither is root and neither is leaf, OR one is root and the other is not a leaf, OR one is a leaf and the other is not a root.
        if (not is_req1_root and not is_req1_leaf and not is_req2_root and not is_req2_leaf) or \
           (is_req1_root and not is_req2_leaf) or \
           (is_req1_leaf and not is_req2_root) or \
           (is_req2_root and not is_req1_leaf) or \
           (is_req2_leaf and not is_req1_root):
            label = 1
        else:
            label = 0


        formatted_pair = {
            'text': f"{req1['Requirement_Text']} [SEP] {req2['Requirement_Text']}",
            'label': label
        }
        training_data.append(formatted_pair)

print(f"Generated {len(training_data)} training pairs.")

"""## Split data

### Subtask:
Split the prepared data into training and validation sets.

**Reasoning**:
Split the prepared training data into training and validation sets using train_test_split from sklearn.
"""

from sklearn.model_selection import train_test_split

texts = [pair['text'] for pair in training_data]
labels = [pair['label'] for pair in training_data]

train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts,
    labels,
    test_size=0.2,  # 20% for validation
    random_state=42,
    stratify=labels  # Stratify to maintain class distribution
)

print(f"Training set size: {len(train_texts)}")
print(f"Validation set size: {len(val_texts)}")

"""## Load and prepare roberta model

### Subtask:
Load a pre-trained RoBERTa model and tokenizer for sequence classification and prepare the data for the model by tokenizing and creating input tensors.

**Reasoning**:
Import necessary libraries and classes for using a pre-trained RoBERTa model, load the model and tokenizer, tokenize the training and validation texts, and prepare input tensors and label tensors.
"""

from transformers import RobertaForSequenceClassification, RobertaTokenizer
import torch

# Load a pre-trained RoBERTa model and tokenizer
model_name = 'roberta-base'  # Or your fine-tuned model path
tokenizer = RobertaTokenizer.from_pretrained(model_name)

# Assuming binary classification, num_labels should be 2
num_labels = 2 # Binary classification (dependent or not dependent)
model = RobertaForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

# Create a custom dataset class
class RequirementDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        # Ensure labels are long
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx]).long()
        return item

    def __len__(self):
        return len(self.labels)

train_encodings = tokenizer(train_texts, truncation=True, padding=True)
val_encodings = tokenizer(val_texts, truncation=True, padding=True)

train_dataset = RequirementDataset(train_encodings, train_labels)
val_dataset = RequirementDataset(val_encodings, val_labels)

print("Data prepared for RoBERTa model.")

"""## Train roberta model

### Subtask:
Train the RoBERTa model on the training data and evaluate it on the validation set.

**Reasoning**:
Define the training arguments, initialize the Trainer, train the model, and evaluate it.
"""

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=1,              # number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=64,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
    eval_strategy="epoch",     # evaluate each epoch - Corrected parameter name
    save_strategy="epoch",           # Save checkpoint every epoch
    load_best_model_at_end=True,     # Load the best model at the end of training
)

# Initialize the Trainer
trainer = Trainer(
    model=model,                         # the instantiated Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=val_dataset             # evaluation dataset
)

print("Model, Training Arguments, and Trainer initialized.")

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(eval_results)


from google.colab import files

# After training is complete, save the model and tokenizer locally
model_save_path = "./roberta_dependency_model"
tokenizer_save_path = "./roberta_dependency_tokenizer"

# Save the trained model and tokenizer
trainer.save_model(model_save_path)
tokenizer.save_pretrained(tokenizer_save_path)

print(f"Trained model saved to: {model_save_path}")
print(f"Tokenizer saved to: {tokenizer_save_path}")

# To download the saved model and tokenizer directories:
print("Downloading model and tokenizer directories...")

# Zip the directories
!zip -r roberta_dependency_model.zip roberta_dependency_model/
!zip -r roberta_dependency_tokenizer.zip roberta_dependency_tokenizer/

# Download the zipped files
files.download('roberta_dependency_model.zip')
files.download('roberta_dependency_tokenizer.zip')

"""## Save model and tokenizer

### Subtask:
Save the trained RoBERTa model and tokenizer to files so they can be loaded later in a different environment.

**Reasoning**:
Save the trained RoBERTa model and tokenizer to specified directories.
"""